// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// LyricsTranslator is an autogenerated mock type for the LyricsTranslator type
type LyricsTranslator struct {
	mock.Mock
}

// TranslateLyrics provides a mock function with given fields: ctx, lyrics
func (_m *LyricsTranslator) TranslateLyrics(ctx context.Context, lyrics []string) ([]string, error) {
	ret := _m.Called(ctx, lyrics)

	if len(ret) == 0 {
		panic("no return value specified for TranslateLyrics")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]string, error)); ok {
		return rf(ctx, lyrics)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []string); ok {
		r0 = rf(ctx, lyrics)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, lyrics)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLyricsTranslator creates a new instance of LyricsTranslator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLyricsTranslator(t interface {
	mock.TestingT
	Cleanup(func())
}) *LyricsTranslator {
	mock := &LyricsTranslator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
