// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// LyricsProvider is an autogenerated mock type for the LyricsProvider type
type LyricsProvider struct {
	mock.Mock
}

// Lyrics provides a mock function with given fields: ctx, artist, title
func (_m *LyricsProvider) Lyrics(ctx context.Context, artist string, title string) ([]string, error) {
	ret := _m.Called(ctx, artist, title)

	if len(ret) == 0 {
		panic("no return value specified for Lyrics")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return rf(ctx, artist, title)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = rf(ctx, artist, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, artist, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLyricsProvider creates a new instance of LyricsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLyricsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *LyricsProvider {
	mock := &LyricsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
