services:
  app:
    container_name: lyrics-library
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:8080"
    env_file: .env
    environment:
      - CONFIG_PATH=/app/.env
    volumes:
      - lyrics_mod_cache:/go/pkg/mod
      - ./:/app
    networks:
      - backend-network
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  migrate:
    container_name: lyrics-migrate
    image: migrate/migrate:v4.18.2
    volumes:
      - ./migrations:/migrations
    command:
      -path=./migrations
      -database=postgres://${DB_USER}:${DB_PASSWORD}@lyrics-postgres:5432/${DB_NAME}?sslmode=disable
      up
    networks:
      - backend-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: lyrics-postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - lyrics_pg_data:/var/lib/postgresql/data
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: lyrics-redis
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - lyrics_redis_data:/data
    networks:
      - backend-network
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}

volumes:
  lyrics_pg_data:
  lyrics_redis_data:
  lyrics_mod_cache:

networks:
  backend-network:
    name: backend-network
    external: true
